#
# ActiveRecord::Turntable configuration file
#

development:
  clusters:
    user_cluster:
      algorithm: modulo
      seq:
        user_seq:
          seq_type: mysql
          connection: user_seq_1
      shards:
        - connection: user_shard_1
        - connection: user_shard_2
        - connection: user_shard_3

test:
  clusters:
    user_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          connection: user_seq
      shards:
        - connection: user_shard_1
          less_than: 20000
        - connection: user_shard_2
          less_than: 40000
        - connection: user_shard_3
          less_than: 10000000

production:
  clusters:
    user_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          connection: user_seq
      shards:
        - connection: user_shard_1
          less_than: 20000
        - connection: user_shard_2
          less_than: 40000
        - connection: user_shard_3
          less_than: 10000000
